### ISSUE TITLE
the anaconda navigator dose not open

### ISSUE THREAD

**Issue by bluesky66** [harvimt/quamash#122]
I tried a lot but I get the below error. I did many solutions but did not work. Thanks

below is the error:

(base) C:\Users\mohammze>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\mohammze\Anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\Anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\...\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\...\Anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\...\Anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by sbourdeauducq** [comment]
This is not a quamash issue, looks more like a conda issue.
