### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by jose1711** [harvimt/quamash#125]
```
python setup.py build
Traceback (most recent call last):
  File "/home/jose/tmp/python-quamash-git/src/quamash/setup.py", line 2, in <module>
    import quamash
  File "/home/jose/tmp/python-quamash-git/src/quamash/quamash/__init__.py", line 594, in <module>
    from ._unix import _SelectorEventLoop
  File "/home/jose/tmp/python-quamash-git/src/quamash/quamash/_unix.py", line 44, in <module>
    class _SelectorMapping(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```
```
$ python --version
Python 3.10.1
```

**Comment by harvimt** [comment]
3.10 isn't supported. See README.

PRs accepted.
