### ISSUE TITLE
Module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by adamesalles** [harvimt/quamash#133]
When trying to install the aur package on Arch, I get this error during build():
```
Traceback (most recent call last):
  File "/home/adame/.cache/paru/clone/python-quamash/src/Quamash-0.6.1/setup.py", line 2, in <module>
    import quamash
  File "/home/adame/.cache/paru/clone/python-quamash/src/Quamash-0.6.1/quamash/__init__.py", line 594, in <module>
    from ._unix import _SelectorEventLoop
  File "/home/adame/.cache/paru/clone/python-quamash/src/Quamash-0.6.1/quamash/_unix.py", line 44, in <module>
    class _SelectorMapping(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

This can be an issue related to Python's version. I may inspect this in the future.

**Comment by harvimt** [comment]
This is fixed in the master branch, but not in PyPI.

Updated versions will not be uploaded to PyPI until the automated tests pass. PRs accepted.
