### ISSUE TITLE
Modal dialogs stops the asyncio event loop

### ISSUE THREAD

**Issue by Insoleet** [harvimt/quamash#41]
Here is a simple test file : 

```python
import sys
import unittest
import os
import asyncio
import quamash
import logging
from PyQt5.QtWidgets import QDialog, QMessageBox
from PyQt5.QtCore import Qt
from PyQt5.QtTest import QTest


class Dialog(QDialog):
    def __init__(self):
        super().__init__()

    @asyncio.coroutine
    def message_box(self):
        result = QMessageBox.question(self, "Test", "Do I bug ?")
        return result


class TestBug(unittest.TestCase):
    def setUp(self):
        self.qapplication = quamash.QApplication(sys.argv)
        self.lp = quamash.QEventLoop(self.qapplication)
        asyncio.set_event_loop(self.lp)

    def tearDown(self):
        try:
            self.lp.close()
        finally:
            asyncio.set_event_loop(None)

    def test_bug(self):
        dialog = Dialog()
        @asyncio.coroutine
        def exec_test():
            asyncio.async(dialog.message_box())
            yield from asyncio.sleep(3)
            for widget in quamash.QApplication.topLevelWidgets():
                if isinstance(widget, QMessageBox):
                    QTest.mouseClick(widget.button(QMessageBox.Yes), Qt.LeftButton)
            yield from asyncio.sleep(1)

        self.lp.run_until_complete(asyncio.wait_for(exec_test(), timeout=10))

if __name__ == '__main__':
    logging.basicConfig( stream=sys.stderr )
    logging.getLogger().setLevel( logging.DEBUG )
    unittest.main()
```

This outputs : 
```
/usr/bin/python3.4 /home/inso/bin/pycharm-4.5.4/helpers/pycharm/utrunner.py /home/inso/code/ucoin/cutecoin/src/cutecoin/tests/process_cfg_community/test_bug.py true
Testing started at 16:44 ...
Exception in callback Task._step()
handle: <Handle Task._step()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 282, in _step
    self.__class__._current_tasks.pop(self._loop)
KeyError: <QEventLoop running=True closed=False debug=False>

Error
Traceback (most recent call last):
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/tests/process_cfg_community/test_bug.py", line 47, in test_bug
    self.lp.run_until_complete(asyncio.wait_for(exec_test(), timeout=10))
  File "/usr/lib/python3.4/site-packages/quamash/__init__.py", line 291, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

Task was destroyed but it is pending!
task: <Task pending coro=<wait_for() done, defined at /usr/lib/python3.4/asyncio/tasks.py:340> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<exec_test() running at /home/inso/code/ucoin/cutecoin/src/cutecoin/tests/process_cfg_community/test_bug.py:45> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_release_waiter(<Future pendi...sk._wakeup()]>)() at /usr/lib/python3.4/asyncio/tasks.py:335]>

Process finished with exit code 0
```

I think it's due to this behaviour of QMessageBoxes : 

>  As a special case, modal widgets like QMessageBox can be used before calling exec(), because modal widgets use their own local event loop.

http://doc.qt.io/qt-5.5/qeventloop.html

**Comment by Insoleet** [comment]
It happens with every modal dialog.

**Comment by harvimt** [comment]
We've contemplated a "helper" method that works something like this

```python
def function modalDialog(dialog):
    future = asyncio.Future()
    dialog.finished.connect(lambda r: future.set_result(r))
    dialog.open()
    return future()
```

It means you can't use the static public helper functions though.

**Comment by Insoleet** [comment]
Is it possible to use the result of "exec_()" method of QDialogs with such a helper function ?

**Comment by harvimt** [comment]
Isn't the int sent to the `finished` signal the same as the int returned by `exec`? (no need for the underscore in Python 3)

basically setup with:

```python
dialog = QMessageBox(...)
dialog.setTitle(...)
```
then doing either
```python
result = dialog.exec()
```
or this
```python
result = yield from modalDialog(dialog)
```
should result in the same thing... I think.
I remember doing this with FileChooser dialogs.

**Comment by harvimt** [comment]
full example
```python
import sys
import itertools
from PyQt5.QtWidgets import QApplication, QMessageBox
#from PyQt5.QtCore import
import asyncio
import quamash 

def dialog_async_exec(dialog):
    future = asyncio.Future()
    dialog.finished.connect(lambda r: future.set_result(r))
    dialog.open()
    return future

@asyncio.coroutine
def main():
    global app
    dialog = QMessageBox(QMessageBox.Question,
                         "Application Name",
                         "Hardware failure.\n\nDisk error detected\nDo you want to stop?")

    dialog.addButton(QMessageBox.Yes)
    dialog.setDefaultButton(QMessageBox.Yes)
    dialog.addButton(QMessageBox.No)
    dialog.setEscapeButton(QMessageBox.No)
    result = yield from dialog_async_exec(dialog)
    if result == QMessageBox.Yes:
        print('Yes!')
    elif result == QMessageBox.No:
        print('No!')
    else:
        print('Something else')

@asyncio.coroutine
def weirdloop():
    # this keeps looping to prove the loop is still running
    for i in itertools.count():
        print('loop count', i)
        yield from asyncio.sleep(1)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    loop = quamash.QEventLoop(app)
    asyncio.set_event_loop(loop)
    asyncio.async(weirdloop())
    with loop:
        loop.run_until_complete(main())
```

**Comment by Insoleet** [comment]
Ok thanks. I wonder if quamash could implements such methods, like : 

```python
from quamash import QMessageBox

....

yield from QMessageBox.async_question(self, "Test", "Do I bug ?")
```

**Comment by harvimt** [comment]
oh, it certainly something that could be done... it would just be a lot of
code to write.
I'd probably put it in `quamash.utils` and not in the main package though.
I'd certainly accept a PR.

**Comment by wolfgang-noichl** [comment]
Ubuntu 18.04,
Python 3.6.5
Quamash 0.6.1
pyqt5 5.9.2

(same for some version on windows, ask if interested...)

Interestingly, https://github.com/harvimt/quamash/issues/41#issuecomment-138034841 now seems to work as well just with `dialog.exec()` (loop continues). However, at least sometimes there are errors like

```python
Exception in callback <TaskStepMethWrapper object at 0x7fe51e40c470>()
handle: <Handle <TaskStepMethWrapper object at 0x7fe51e40c470>()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <QSelectorEventLoop running=True closed=False debug=False>
```

Which are then, if one doesn't know about this issue here, quite hard to identify and fix :smile:
