### ISSUE TITLE
easycallback doctest is broken ?

### ISSUE THREAD

**Issue by Insoleet** [harvimt/quamash#58]
When I run pytest, I get : 
```
2015-12-10 20:42:18,690 - DEBUG - quamash.QEventLoop - Adding reader callback for file descriptor 10
2015-12-10 20:42:18,690 - DEBUG - quamash.QEventLoop - Running <generator object coro at 0x7f76c782b5a0> until complete
2015-12-10 20:42:18,690 - DEBUG - quamash.QEventLoop - Registering callback <bound method Task._step of <Task pending coro=<coro() running at /home/inso/.pyenv/versions/3.4.3/lib/python3.4/asyncio/coroutines.py:139>>> to be invoked with arguments () after 0 second(s)
2015-12-10 20:42:18,691 - DEBUG - quamash.QEventLoop - Adding callback <Handle Task._step()> with delay 0
2015-12-10 20:42:18,691 - DEBUG - quamash.QEventLoop - Starting Qt event loop
2015-12-10 20:42:18,691 - DEBUG - quamash.QEventLoop - Callback timer fired, calling <Handle Task._step()>
Traceback (most recent call last):
  File "/home/inso/code/quamash/quamash/__init__.py", line 214, in <lambda>
    signaler.signal.connect(lambda self, args, kwargs: fn(self, *args, **kwargs))
  File "<doctest quamash._easycallback[5]>", line 6, in mycallback
AssertionError: assert <PyQt5.QtCore.QThread object at 0x7f76c7c74dc8> is not global_thread
[1]    14537 abort (core dumped)  py.test -s tests/test_qeventloop.py
```

**Comment by Insoleet** [comment]
It seems that I have a problem with `@easycallback` . The test is broken, but the following test, not using easycallback, runs nicely : 

```python

import asyncio

import quamash
QThread, QObject = quamash.QtCore.QThread, quamash.QtCore.QObject
from PyQt5.QtCore import pyqtSignal
app = quamash.QApplication([])

global_thread = QThread.currentThread()
called = False
class MyObject(QObject):
    def mycallback(self):
        global global_thread, mythread, called
        cur_thread = QThread.currentThread()
        assert cur_thread is not global_thread
        assert cur_thread is mythread
        called = True

class Signalizer(QObject):
    signaling = pyqtSignal()

mythread = QThread()
mythread.start()
myobject = MyObject()
myobject.moveToThread(mythread)
signer = Signalizer()
signer.signaling.connect(myobject.mycallback)

@asyncio.coroutine
def mycoroutine():
    signer.signaling.emit()

loop = quamash.QEventLoop(app)
asyncio.set_event_loop(loop)
with loop:
    loop.run_until_complete(mycoroutine())
assert called is True
```

I'm using PyQt5 5.5.1 and python 3.4.3.

**Comment by harvimt** [comment]
_easycallback will probably be removed in future versions of Quamash, so I
wouldn't rely on it.

This code:
https://github.com/harvimt/quamash/blob/depinject5realz/quamash/__init__.py#L133-L142
is used instead.

**Comment by harvimt** [comment]
and by probably I mean the next version :smile:
