### ISSUE TITLE
Non-ASCII Charactor

### ISSUE THREAD

**Issue by RyanWangGit** [harvimt/quamash#64]
I'm current't using OSX and trying to install quamash using 
```
pip install quamash
```
However I kept getting this
```
Collecting quamash
  Using cached Quamash-0.5.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xc/w91zg1p97dd4v2gzrlrp7t440000gn/T/pip-build-VDDZTx/quamash/setup.py", line 2, in <module>
        import quamash
      File "/private/var/folders/xc/w91zg1p97dd4v2gzrlrp7t440000gn/T/pip-build-VDDZTx/quamash/quamash/__init__.py", line 1
    SyntaxError: Non-ASCII character '\xc2' in file /private/var/folders/xc/w91zg1p97dd4v2gzrlrp7t440000gn/T/pip-build-VDDZTx/quamash/quamash/__init__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by harvimt** [comment]
Only works on python 3.

**Comment by harvimt** [comment]
see #49

**Comment by converge** [comment]
pip3 install quamash do the work in macOS

**Comment by harvimt** [comment]
try `python3 --version`  and `python3 -m pip install quamash`
